### ISSUE TITLE
prepareModel encountered an unexpected runtime exception -  object has no attribute 'has_env'

### ISSUE THREAD

**Issue by maalbico** [oracle/weblogic-toolkit-ui#252]
Hi all I'm following the quickstart link you have in https://oracle.github.io/weblogic-toolkit-ui

I was able to validate the model correctly.

![image](https://github.com/oracle/weblogic-toolkit-ui/assets/66915465/38cc9b6f-4c1f-4519-a923-256c76e0a959)

I reviewed, zip files, properties file and model file the tools generate me, everything seems to be ok,
But when I try to prepare the model, I got following message.

AttributeError: 'string'

####<Mar 20, 2024 10:31:08 AM> <SEVERE> <prepare_model> <main> <WLSDPLY-20035> <prepareModel encountered an unexpected runtime exception.  Please file an issue on GitHub and attach the log file and stdout. Exception: exceptions.AttributeError
AttributeError: 'string' object has no attribute 'has_env'
Traceback (most recent call last):
  File "C:\PROGRA~1\WEBLOG~1\tools\WEBLOG~1\lib\python\wlsdeploy\util\tool_main.py", line 52, in run_tool
    exit_code = main(model_context_obj)
  File "C:\PROGRA~1\WEBLOG~1\tools\WEBLOG~1\lib\python\prepare_model.py", line 80, in main
    obj.prepare_models()
  File "C:\PROGRA~1\WEBLOG~1\tools\WEBLOG~1\lib\python\wlsdeploy\tool\prepare\model_preparer.py", line 391, in prepare_models
    variables.substitute(merged_model_dictionary, result_variable_map, self.model_context)
  File "C:\PROGRA~1\WEBLOG~1\tools\WEBLOG~1\lib\python\wlsdeploy\util\variables.py", line 201, in substitute
    _process_node(dictionary, variables, model_context, error_info)
  File "C:\PROGRA~1\WEBLOG~1\tools\WEBLOG~1\lib\python\wlsdeploy\util\variables.py", line 232, in _process_node
    _process_node(value, variables, model_context, error_info)
  File "C:\PROGRA~1\WEBLOG~1\tools\WEBLOG~1\lib\python\wlsdeploy\util\variables.py", line 232, in _process_node
    _process_node(value, variables, model_context, error_info)
  File "C:\PROGRA~1\WEBLOG~1\tools\WEBLOG~1\lib\python\wlsdeploy\util\variables.py", line 232, in _process_node
    _process_node(value, variables, model_context, error_info)
  File "C:\PROGRA~1\WEBLOG~1\tools\WEBLOG~1\lib\python\wlsdeploy\util\variables.py", line 232, in _process_node
    _process_node(value, variables, model_context, error_info)
  File "C:\PROGRA~1\WEBLOG~1\tools\WEBLOG~1\lib\python\wlsdeploy\util\variables.py", line 232, in _process_node
    _process_node(value, variables, model_context, error_info)
  File "C:\PROGRA~1\WEBLOG~1\tools\WEBLOG~1\lib\python\wlsdeploy\util\variables.py", line 232, in _process_node
    _process_node(value, variables, model_context, error_info)
  File "C:\PROGRA~1\WEBLOG~1\tools\WEBLOG~1\lib\python\wlsdeploy\util\variables.py", line 232, in _process_node
    _process_node(value, variables, model_context, error_info)
  File "C:\PROGRA~1\WEBLOG~1\tools\WEBLOG~1\lib\python\wlsdeploy\util\variables.py", line 241, in _process_node
    nodes[key] = _substitute(value, variables, model_context, error_info, key)
  File "C:\PROGRA~1\WEBLOG~1\tools\WEBLOG~1\lib\python\wlsdeploy\util\variables.py", line 288, in _substitute
    if is_windows and not env_helper.has_env(env_var_name) and env_var_name.has_env(env_var_name.upper()):
AttributeError: 'string' object has no attribute 'has_env'

 But I'm not able to find out what is this has_env this model needs. 

Please your help.
The model source code:

domainInfo:
    AdminUserName: '@@PROP:WebLogicAdminUserName@@'
    AdminPassword: '@@PROP:WebLogicAdminPassword@@'
topology:
    ServerTemplate:
        todo_srv_template:
            ListenPortEnabled: true
            Cluster: mycluster
    Cluster:
        mycluster:
            DynamicServers:
                ServerTemplate: todo_srv_template
                ServerNamePrefix: 'ToDoServer-'
                DynamicClusterSize: 10
                MaxDynamicClusterSize: 10
                CalculatedListenPorts: false
    Name: todolist_domain
    ProductionModeEnabled: true
    AdministrationPortEnabled: true
resources:
    JDBCSystemResource:
        myDataSource:
            JdbcResource:
                JDBCDriverParams:
                    Properties:
                        user:
                            Value: admin
                    DriverName: com.mysql.cj.jdbc.Driver
                    URL: 'jdbc:mysql://mysql:3306/tododb'
                    PasswordEncrypted: admin
                JDBCConnectionPoolParams:
                    TestConnectionsOnReserve: true
                    TestTableName: ToDos
                JDBCDataSourceParams:
                    JNDIName: [
                        jdbc/ToDoDB
                    ]
                    
                DatasourceType: GENERIC
            Target: [
                mycluster
            ]
            
appDeployments:
    Application:
        todo:
            Target: [
                mycluster
            ]
            SourcePath: wlsdeploy/applications/todo.war

Log File:

[prepareModel.log](https://github.com/oracle/weblogic-toolkit-ui/files/14669884/prepareModel.log)

**Comment by robertpatrick** [comment]
@maalbico I apologize for just seeing this issue.  This is indeed a WDT bug.  Unfortunately, I just released WDT 4.0.1 last night so this fix will be part of WDT 4.0.2.
